name: cyberai
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.7
  - numpy
  - matplotlib
  - pandas
  - seaborn
  - jupyterlab
  - scikit-learn
  - pip
  - pip:
      - librosa
      - hyperopt
      - bayesian-optimization
      - scikit-optimize



